### ISSUE TITLE
한국 주 추가

### ISSUE THREAD

**Issue by Bearcamp1962** [MRN-HOI4/hotwar#3]
북한 - 평북, 평남, 평양, 황남, 황북, 남강, 함남, 함북, 양강, 자강
남한 - 경기, 강원, 충북, 충남, 경북, 경남, 전북, 전남, 서울, 부산, 제주

**Comment by Bearcamp1962** [comment]
제주도를 섬으로 ( 안이어진거)

**Comment by Bearcamp1962** [comment]
기본적으로 기존 주는 -북도로

**Comment by evon27** [comment]
광역시 추가하면 고증 안맞지 않음?
